### ISSUE TITLE
new stuff for map editor game packs

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/unvanquished-mapeditor-support#1]
Hey, I updated the files… but not only.

I extracted the build tool to a separate repository, this way it can be used by other projects who wants to target both GtkRadiant and NetRadiant.

I temporarily uploaded on my own GitHub space the relevant repositories:
- assets only: https://github.com/illwieckz/unvanquished-mapeditor-support
- code only: https://github.com/illwieckz/mkeditorpacks

If you are OK with that, these repositories can migrate inside the Unvanquished organisation.

The git submodule is not done yet because the repository url will change, but the `mkeditorpacks` just have to be a git submodule of `Unvanquished-editorpacks` then you run `make`.

**Comment by mjstahlberg** [comment]
- The `mkeditorpacks` repo should go to @DaemonDevelopers instead of @Unvanquished.
- I would prefer one of the more verbose "mapeditor-support", "mapeditor-module" or "mapeditor-package" over "Unvanquished-editorpacks". (The "Unvanquished" is superfluous as the repository will be located at the Unvanquished organization.)
- Go ahead!

**Comment by illwieckz** [comment]
> - The `mkeditorpacks` repo should go to @DaemonDevelopers instead of @Unvanquished.

You're right! It's a better place for this kind of thing. :+1: 

> - I would prefer one of the more verbose "mapeditor-support", "mapeditor-module" or "mapeditor-package" over "Unvanquished-editorpacks". (The "Unvanquished" is superfluous as the repository will be located at the Unvanquished organization.)

I named that repo with an explicit reference to unvanquished since I uploaded it on my own profile (it has to be published somewhere if we want to discuss it) and I was not happy to put a name that doesn't tell what is for. Like I said on IRC:

> [illwieckz] I don't like reusable names for non-reusable things :p
> [illwieckz] btw, do what you prefer

The point is that organization name is a github thing, not a repository thing, by default `git` keeps the repository name on `clone`, not the organization name, because it's not a repository thing. By default, we all assume that a repository having the same name that another repository is a fork of the other one, regardless of organization or hosting.

The organization name is not kept when people fork a project on GitHub to contribute to, so people will have repositories that don't tell what they are for. If other projects do the same, it will lead to absurd conflict like people not being able to fork an hypothetic `etlegacy/mapeditor-support` just because they already forked `unvanquished/mapeditor-support`, the two things having not the same _purpose_, being not a variant of something that produces the _same result_ but just something else that just do _like another do_, like if the `ntoskrnl.exe` file was named `vmlinuz` just because they are both kernels, and you can still look at the organization name on the web page to know they share nothing.  :stuck_out_tongue_closed_eyes:

On my hard drive I have plenty of repositories like `chameleon`, `crunch`, `daemonmap`,  `etlegacy`, `mantis`, `mkeditorpacks`, `netradiant`, `netradiant-xonoticpack`,  `sloth`, `unvanquished`, `xonotic`, `xonotic-data`, `xqf`, and in the middle of that, a `mapeditor-support` thing that does not tell what is it for. Of course I can rename it, but why not renaming it at the first place, _one time for everyone_?

When you create a repository on GitHub, it suggests you names like `furry-broccoli`, `shiny-waffle` or `cuddly-octo-pancake` just because it's better for everyone if we don't use too generic names that collide with other names.

So, do what you prefer, but I'm not happy with reusable names for non-reusable things. :wink:

**Comment by illwieckz** [comment]
@Viech I have a question for you there: https://github.com/Unvanquished/mapeditor-support/commit/34dca8c079e8e4ba753d729dac8f57157aa6db20#commitcomment-19445387

**Comment by mjstahlberg** [comment]
Make it `unvanquished-mapeditor-support` then. :stuck_out_tongue:

**Comment by illwieckz** [comment]
issues discussed in this thread are now discussed in PR #2 and  issue #3. closing this one.
