### ISSUE TITLE
Supports 2ds models instead of 3ds

### ISSUE THREAD

**Issue by zturtleman** [Unvanquished/unvanquished-mapeditor-support#16]
[src/gamefile/vfs.yaml](https://github.com/Unvanquished/unvanquished-mapeditor-support/blob/master/src/gamefile/vfs.yaml) lists 2ds as a supported model format extension. I think it's suppose to be 3ds (Autodesk 3ds Max). Searching [netradiant source code](https://gitlab.com/xonotic/netradiant) for 2ds has 0 results but 3ds has many results.

**Comment by illwieckz** [comment]
nice catch!

**Comment by illwieckz** [comment]
especially because we test for it being `3ds`:

https://github.com/Unvanquished/unvanquished-mapeditor-support/blob/2ec1a3714af425bca6c825c31a4ab5daff56ccbc/mkeditorpacks/bin/gamefile#L48

now fixed.
