### ISSUE TITLE
Simplest way to create map from Sketchfab?

### ISSUE THREAD

**Issue by stevennt** [Unvanquished/unvanquished-mapeditor-support#18]
What would be the easiest way to import a map, say from Sketchfab, to Unvanquished?
Lets say the map is a tube like below. Any tip? Thanks.

https://sketchfab.com/3d-models/metro-tube-46b6647a48c74a05a793875a3baf045a

**Comment by illwieckz** [comment]
The recommended map editor, NetRadiant, knows how to import `.obj` and `.ase` files.

You'll find my most recent Linux build there:  
https://forums.xonotic.org/showthread.php?tid=8108&pid=85047#pid85047
Or you can build it from source by following instructions there:  
https://gitlab.com/xonotic/netradiant#getting-the-sources
Note that if you build NetRadiant from source you'll miss the tool to compute (optional) navigation meshes for bots, you can find source for it there:  
https://github.com/DaemonEngine/daemonmap

So the idea is to export your Sketchfab model as `.ase` or `.obj` (I don't know what is better), import it in NetRadiant and build the `.map` with `q3map2` map compiler (shipped with NetRadiant) like other idtech3 games.

**Comment by illwieckz** [comment]
Note that model has a lot of faces, it may be good to set all of them as _details_ ones and put them within some simple structural brushes.
