### ISSUE TITLE
Import existing map from Autocad DMG?

### ISSUE THREAD

**Issue by stevennt** [Unvanquished/unvanquished-mapeditor-support#19]
Does it make sense (and is it possible currently) to import an existing map from Autocad DMG file? The idea is to speed up map development and to provide a game scene in familiar buildings / cities / tunnels.

**Comment by illwieckz** [comment]
As said in #18, if you find a way to convert it to `.ase` and `.obj` it may be importable in netradiant editor.
Note that forums are a better place for this kind of question.
