### ISSUE TITLE
rename to unvanquished-mapeditor-support

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/unvanquished-mapeditor-support#3]
looks to be redundant when giving url with organization name, but as discussed in #1, it's problematic when you fork repository to known from which game it comes. For example to make my pull request I forked this repository then renamed it because `github.com/illwieckz/mapeditor-support` means nothing (and if one day I want to PR to another mapeditor-support for other game, I will not be able to clone).

The current repository url is not used by both GtkRadiant and NetRadiant, no one had code to fetch it merged yet, so it's safe to rename at this time.

**Comment by mjstahlberg** [comment]
I'm fine with that. We also have `unvanquished-master` so it's somewhat consistent, too.
